### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by bG9sIHVyIGhvbW8** [notrhys/Lite#6]
Instructions on setting up are a bit vague, so I'm having trouble compiling the source code and running it. How do I install & use Lite Client?

**Comment by Numzskull** [comment]
You grow a brain.

**Comment by bossatron1311** [comment]
> You grow a brain.

how do i use

**Comment by chirag350** [comment]
git clone https://github.com/notrhys/Lite.git
cd Lite
mvn
and then copy the stuff into versions

**Comment by bossatron1311** [comment]
> git clone https://github.com/notrhys/Lite.git
> cd Lite
> mvn
> and then copy the stuff into versions

for windows?

**Comment by chirag350** [comment]
Just use linux

**Comment by bossatron1311** [comment]
> Just use linux

i dont have a linux vm

**Comment by chirag350** [comment]
> i dont have a linux vm
You don't need one? Just download ubuntu iso, flash a usb and boot into it, no need to install

**Comment by notrhys** [comment]
or just download the version from https://liteclient.club/
